### ISSUE TITLE
Blank response

### ISSUE THREAD

**Issue by danielfornez** [estephinson/certbot-cwp#1]
Hi i try to create a new SSL Certificate and i dont  recive a response from the module.

![image](https://cloud.githubusercontent.com/assets/9473541/16543777/567875ae-40b7-11e6-8012-860b331b12c1.png)

**Comment by estephinson** [comment]
Have you installed certbot on your server? If not, follow the guide [here](http://forum.centos-webpanel.com/ssl/short-let's-encrypt-guide-on-centos-6-x/).

If you have, check that CERTBOT_PATH is defined to where it is installed.

**Comment by estephinson** [comment]
Closed as CWP have made their own Let's Encrypt manager
